/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorsRepresentativesRecord extends org.jooq.impl.TableRecordImpl<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1070380307;

	/**
	 * Setter for <code>PUBLIC.ACTORS_REPRESENTATIVES.ACTOR_ID</code>. 
	 */
	public void setActorId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.ACTORS_REPRESENTATIVES.ACTOR_ID</code>. 
	 */
	public java.lang.Long getActorId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.ACTORS_REPRESENTATIVES.REPRESENTATIVE_ID</code>. 
	 */
	public void setRepresentativeId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.ACTORS_REPRESENTATIVES.REPRESENTATIVE_ID</code>. 
	 */
	public java.lang.Long getRepresentativeId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.ACTORS_REPRESENTATIVES.PURCHASE_ID</code>. 
	 */
	public void setPurchaseId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.ACTORS_REPRESENTATIVES.PURCHASE_ID</code>. 
	 */
	public java.lang.Long getPurchaseId() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.ACTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.REPRESENTATIVE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.PURCHASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getActorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getRepresentativeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getPurchaseId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActorsRepresentativesRecord
	 */
	public ActorsRepresentativesRecord() {
		super(net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES);
	}
}
