/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactsRecord extends org.jooq.impl.TableRecordImpl<net.phobot.realestate.model.tables.records.ContactsRecord> implements org.jooq.Record2<java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -2093033456;

	/**
	 * Setter for <code>PUBLIC.CONTACTS.EMAIL</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.CONTACTS.EMAIL</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.CONTACTS.ACTOR_ID</code>. 
	 */
	public void setActorId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.CONTACTS.ACTOR_ID</code>. 
	 */
	public java.lang.Long getActorId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.phobot.realestate.model.tables.Contacts.CONTACTS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return net.phobot.realestate.model.tables.Contacts.CONTACTS.ACTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getActorId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContactsRecord
	 */
	public ContactsRecord() {
		super(net.phobot.realestate.model.tables.Contacts.CONTACTS);
	}
}
