/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SignaturesRecord extends org.jooq.impl.TableRecordImpl<net.phobot.realestate.model.tables.records.SignaturesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.sql.Date> {

	private static final long serialVersionUID = 209784500;

	/**
	 * Setter for <code>PUBLIC.SIGNATURES.DOCUMENT_ID</code>. 
	 */
	public void setDocumentId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.SIGNATURES.DOCUMENT_ID</code>. 
	 */
	public java.lang.Long getDocumentId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.SIGNATURES.ACTOR_ID</code>. 
	 */
	public void setActorId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.SIGNATURES.ACTOR_ID</code>. 
	 */
	public java.lang.Long getActorId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.SIGNATURES.DATE</code>. 
	 */
	public void setDate(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.SIGNATURES.DATE</code>. 
	 */
	public java.sql.Date getDate() {
		return (java.sql.Date) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.sql.Date> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.sql.Date> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return net.phobot.realestate.model.tables.Signatures.SIGNATURES.DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return net.phobot.realestate.model.tables.Signatures.SIGNATURES.ACTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return net.phobot.realestate.model.tables.Signatures.SIGNATURES.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getActorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getDate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SignaturesRecord
	 */
	public SignaturesRecord() {
		super(net.phobot.realestate.model.tables.Signatures.SIGNATURES);
	}
}
