/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attorneys extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.AttorneysRecord> {

	private static final long serialVersionUID = -988243857;

	/**
	 * The singleton instance of <code>PUBLIC.ATTORNEYS</code>
	 */
	public static final net.phobot.realestate.model.tables.Attorneys ATTORNEYS = new net.phobot.realestate.model.tables.Attorneys();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.AttorneysRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.AttorneysRecord.class;
	}

	/**
	 * The column <code>PUBLIC.ATTORNEYS.REPRESENTATIVE_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.AttorneysRecord, java.lang.Long> REPRESENTATIVE_ID = createField("REPRESENTATIVE_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.ATTORNEYS</code> table reference
	 */
	public Attorneys() {
		super("ATTORNEYS", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.ATTORNEYS</code> table reference
	 */
	public Attorneys(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_A2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Attorneys as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Attorneys(alias);
	}
}
