/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentTypes extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.DocumentTypesRecord> {

	private static final long serialVersionUID = -541243574;

	/**
	 * The singleton instance of <code>PUBLIC.DOCUMENT_TYPES</code>
	 */
	public static final net.phobot.realestate.model.tables.DocumentTypes DOCUMENT_TYPES = new net.phobot.realestate.model.tables.DocumentTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.DocumentTypesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.DocumentTypesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.DOCUMENT_TYPES.ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.DocumentTypesRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>PUBLIC.DOCUMENT_TYPES.DOC_TYPE</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.DocumentTypesRecord, java.lang.String> DOC_TYPE = createField("DOC_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * Create a <code>PUBLIC.DOCUMENT_TYPES</code> table reference
	 */
	public DocumentTypes() {
		super("DOCUMENT_TYPES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.DOCUMENT_TYPES</code> table reference
	 */
	public DocumentTypes(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.DocumentTypes.DOCUMENT_TYPES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentTypesRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentTypesRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.DocumentTypes as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.DocumentTypes(alias);
	}
}
