/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individuals extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.IndividualsRecord> {

	private static final long serialVersionUID = -91976471;

	/**
	 * The singleton instance of <code>PUBLIC.INDIVIDUALS</code>
	 */
	public static final net.phobot.realestate.model.tables.Individuals INDIVIDUALS = new net.phobot.realestate.model.tables.Individuals();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.IndividualsRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.IndividualsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.INDIVIDUALS.FIRST_NAME</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.IndividualsRecord, java.lang.String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this);

	/**
	 * The column <code>PUBLIC.INDIVIDUALS.LAST_NAME</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.IndividualsRecord, java.lang.String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this);

	/**
	 * The column <code>PUBLIC.INDIVIDUALS.ACTOR_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.IndividualsRecord, java.lang.Long> ACTOR_ID = createField("ACTOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.INDIVIDUALS</code> table reference
	 */
	public Individuals() {
		super("INDIVIDUALS", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.INDIVIDUALS</code> table reference
	 */
	public Individuals(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Individuals as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Individuals(alias);
	}
}
