/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notaries extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.NotariesRecord> {

	private static final long serialVersionUID = -715513571;

	/**
	 * The singleton instance of <code>PUBLIC.NOTARIES</code>
	 */
	public static final net.phobot.realestate.model.tables.Notaries NOTARIES = new net.phobot.realestate.model.tables.Notaries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.NotariesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.NotariesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.NOTARIES.INDIVIDUAL_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.NotariesRecord, java.lang.Long> INDIVIDUAL_ID = createField("INDIVIDUAL_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.NOTARIES</code> table reference
	 */
	public Notaries() {
		super("NOTARIES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.NOTARIES</code> table reference
	 */
	public Notaries(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Notaries.NOTARIES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.NotariesRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_8C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.NotariesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.NotariesRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_8C);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.NotariesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.NotariesRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_8CB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Notaries as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Notaries(alias);
	}
}
