/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.OrganizationsRecord> {

	private static final long serialVersionUID = 1156628598;

	/**
	 * The singleton instance of <code>PUBLIC.ORGANIZATIONS</code>
	 */
	public static final net.phobot.realestate.model.tables.Organizations ORGANIZATIONS = new net.phobot.realestate.model.tables.Organizations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.OrganizationsRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.OrganizationsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.ORGANIZATIONS.NAME</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.OrganizationsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this);

	/**
	 * The column <code>PUBLIC.ORGANIZATIONS.ACTOR_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.OrganizationsRecord, java.lang.Long> ACTOR_ID = createField("ACTOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.ORGANIZATIONS</code> table reference
	 */
	public Organizations() {
		super("ORGANIZATIONS", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.ORGANIZATIONS</code> table reference
	 */
	public Organizations(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_3C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_3C);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Organizations as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Organizations(alias);
	}
}
