/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchases extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.PurchasesRecord> {

	private static final long serialVersionUID = 1227716845;

	/**
	 * The singleton instance of <code>PUBLIC.PURCHASES</code>
	 */
	public static final net.phobot.realestate.model.tables.Purchases PURCHASES = new net.phobot.realestate.model.tables.Purchases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.PurchasesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.PurchasesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.PURCHASES.PURCHASE_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.PurchasesRecord, java.lang.Long> PURCHASE_ID = createField("PURCHASE_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.PURCHASES</code> table reference
	 */
	public Purchases() {
		super("PURCHASES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.PURCHASES</code> table reference
	 */
	public Purchases(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Purchases.PURCHASES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_3B;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_3B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Purchases as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Purchases(alias);
	}
}
