/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RealEstateAgents extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> {

	private static final long serialVersionUID = 1219130980;

	/**
	 * The singleton instance of <code>PUBLIC.REAL_ESTATE_AGENTS</code>
	 */
	public static final net.phobot.realestate.model.tables.RealEstateAgents REAL_ESTATE_AGENTS = new net.phobot.realestate.model.tables.RealEstateAgents();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.RealEstateAgentsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.REAL_ESTATE_AGENTS.REPRESENTATIVE_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, java.lang.Long> REPRESENTATIVE_ID = createField("REPRESENTATIVE_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.REAL_ESTATE_AGENTS</code> table reference
	 */
	public RealEstateAgents() {
		super("REAL_ESTATE_AGENTS", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.REAL_ESTATE_AGENTS</code> table reference
	 */
	public RealEstateAgents(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_DD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_DD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_DD2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.RealEstateAgents as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.RealEstateAgents(alias);
	}
}
