/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Representatives extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.RepresentativesRecord> {

	private static final long serialVersionUID = 960510966;

	/**
	 * The singleton instance of <code>PUBLIC.REPRESENTATIVES</code>
	 */
	public static final net.phobot.realestate.model.tables.Representatives REPRESENTATIVES = new net.phobot.realestate.model.tables.Representatives();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.RepresentativesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.RepresentativesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.REPRESENTATIVES.ACTOR_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.RepresentativesRecord, java.lang.Long> ACTOR_ID = createField("ACTOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.REPRESENTATIVES</code> table reference
	 */
	public Representatives() {
		super("REPRESENTATIVES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.REPRESENTATIVES</code> table reference
	 */
	public Representatives(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_6A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_6A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Representatives as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Representatives(alias);
	}
}
