/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Signatures extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.SignaturesRecord> {

	private static final long serialVersionUID = -736488977;

	/**
	 * The singleton instance of <code>PUBLIC.SIGNATURES</code>
	 */
	public static final net.phobot.realestate.model.tables.Signatures SIGNATURES = new net.phobot.realestate.model.tables.Signatures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.SignaturesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.SignaturesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SIGNATURES.DOCUMENT_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.SignaturesRecord, java.lang.Long> DOCUMENT_ID = createField("DOCUMENT_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>PUBLIC.SIGNATURES.ACTOR_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.SignaturesRecord, java.lang.Long> ACTOR_ID = createField("ACTOR_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>PUBLIC.SIGNATURES.DATE</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.SignaturesRecord, java.sql.Date> DATE = createField("DATE", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * Create a <code>PUBLIC.SIGNATURES</code> table reference
	 */
	public Signatures() {
		super("SIGNATURES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.SIGNATURES</code> table reference
	 */
	public Signatures(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.Signatures.SIGNATURES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.SignaturesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.SignaturesRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_DC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.Signatures as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.Signatures(alias);
	}
}
