/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TitleCompanies extends org.jooq.impl.TableImpl<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> {

	private static final long serialVersionUID = -1312567541;

	/**
	 * The singleton instance of <code>PUBLIC.TITLE_COMPANIES</code>
	 */
	public static final net.phobot.realestate.model.tables.TitleCompanies TITLE_COMPANIES = new net.phobot.realestate.model.tables.TitleCompanies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> getRecordType() {
		return net.phobot.realestate.model.tables.records.TitleCompaniesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.TITLE_COMPANIES.ORGANIZATION_ID</code>. 
	 */
	public final org.jooq.TableField<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, java.lang.Long> ORGANIZATION_ID = createField("ORGANIZATION_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>PUBLIC.TITLE_COMPANIES</code> table reference
	 */
	public TitleCompanies() {
		super("TITLE_COMPANIES", net.phobot.realestate.model.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.TITLE_COMPANIES</code> table reference
	 */
	public TitleCompanies(java.lang.String alias) {
		super(alias, net.phobot.realestate.model.Public.PUBLIC, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> getPrimaryKey() {
		return net.phobot.realestate.model.Keys.CONSTRAINT_8A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_8A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, ?>>asList(net.phobot.realestate.model.Keys.CONSTRAINT_8);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.phobot.realestate.model.tables.TitleCompanies as(java.lang.String alias) {
		return new net.phobot.realestate.model.tables.TitleCompanies(alias);
	}
}
