/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PaymentTypesRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentsRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentTypesRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_2A = UniqueKeys0.CONSTRAINT_2A;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_3B = UniqueKeys0.CONSTRAINT_3B;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> CONSTRAINT_DD = UniqueKeys0.CONSTRAINT_DD;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_2A3 = ForeignKeys0.CONSTRAINT_2A3;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_2A3C5 = ForeignKeys0.CONSTRAINT_2A3C5;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_2A3C = ForeignKeys0.CONSTRAINT_2A3C;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_A2 = ForeignKeys0.CONSTRAINT_A2;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_1 = ForeignKeys0.CONSTRAINT_1;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_14 = ForeignKeys0.CONSTRAINT_14;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_149 = ForeignKeys0.CONSTRAINT_149;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.PaymentTypesRecord> CONSTRAINT_1499 = ForeignKeys0.CONSTRAINT_1499;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ContactsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_C = ForeignKeys0.CONSTRAINT_C;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.DocumentTypesRecord> CONSTRAINT_DE = ForeignKeys0.CONSTRAINT_DE;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_DE55 = ForeignKeys0.CONSTRAINT_DE55;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_DE5 = ForeignKeys0.CONSTRAINT_DE5;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_2AC = ForeignKeys0.CONSTRAINT_2AC;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_3C = ForeignKeys0.CONSTRAINT_3C;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_DD2 = ForeignKeys0.CONSTRAINT_DD2;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_6A = ForeignKeys0.CONSTRAINT_6A;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.SignaturesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_DC = ForeignKeys0.CONSTRAINT_DC;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_8A = ForeignKeys0.CONSTRAINT_8A;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_7 = createUniqueKey(net.phobot.realestate.model.tables.Actors.ACTORS, net.phobot.realestate.model.tables.Actors.ACTORS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord> CONSTRAINT_A = createUniqueKey(net.phobot.realestate.model.tables.Attorneys.ATTORNEYS, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS.REPRESENTATIVE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PaymentTypesRecord> CONSTRAINT_5 = createUniqueKey(net.phobot.realestate.model.tables.PaymentTypes.PAYMENT_TYPES, net.phobot.realestate.model.tables.PaymentTypes.PAYMENT_TYPES.ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentsRecord> CONSTRAINT_D = createUniqueKey(net.phobot.realestate.model.tables.Documents.DOCUMENTS, net.phobot.realestate.model.tables.Documents.DOCUMENTS.ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.DocumentTypesRecord> CONSTRAINT_2 = createUniqueKey(net.phobot.realestate.model.tables.DocumentTypes.DOCUMENT_TYPES, net.phobot.realestate.model.tables.DocumentTypes.DOCUMENT_TYPES.ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_2A = createUniqueKey(net.phobot.realestate.model.tables.Individuals.INDIVIDUALS, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_3 = createUniqueKey(net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_3B = createUniqueKey(net.phobot.realestate.model.tables.Purchases.PURCHASES, net.phobot.realestate.model.tables.Purchases.PURCHASES.PURCHASE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> CONSTRAINT_DD = createUniqueKey(net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS.REPRESENTATIVE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_6 = createUniqueKey(net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> CONSTRAINT_8 = createUniqueKey(net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES.ORGANIZATION_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_2A3 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_2A3C5 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_2A3C = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3B, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.PURCHASE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_A2 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_1 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS.PAYABLE_TO);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_14 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS.BELONGS_TO);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_149 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_2A, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS.IN_POSSESSION_OF);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.CertifiedChecksRecord, net.phobot.realestate.model.tables.records.PaymentTypesRecord> CONSTRAINT_1499 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_5, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS, net.phobot.realestate.model.tables.CertifiedChecks.CERTIFIED_CHECKS.PAYMENT_FOR);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ContactsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_C = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.Contacts.CONTACTS, net.phobot.realestate.model.tables.Contacts.CONTACTS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.DocumentTypesRecord> CONSTRAINT_DE = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_2, net.phobot.realestate.model.tables.Documents.DOCUMENTS, net.phobot.realestate.model.tables.Documents.DOCUMENTS.DOCUMENT_TYPE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_DE55 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3B, net.phobot.realestate.model.tables.Documents.DOCUMENTS, net.phobot.realestate.model.tables.Documents.DOCUMENTS.PURCHASE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.DocumentsRecord, net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_DE5 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_2A, net.phobot.realestate.model.tables.Documents.DOCUMENTS, net.phobot.realestate.model.tables.Documents.DOCUMENTS.IN_POSSESSION_OF);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_2AC = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_3C = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_DD2 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_6A = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.SignaturesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_DC = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_7, net.phobot.realestate.model.tables.Signatures.SIGNATURES, net.phobot.realestate.model.tables.Signatures.SIGNATURES.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_8A = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES.ORGANIZATION_ID);
	}
}
