/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<net.phobot.realestate.model.tables.records.ActorsRecord, java.lang.Long> IDENTITY_ACTORS = Identities0.IDENTITY_ACTORS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> CONSTRAINT_DD = UniqueKeys0.CONSTRAINT_DD;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_6A = UniqueKeys0.CONSTRAINT_6A;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_3C = UniqueKeys0.CONSTRAINT_3C;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_3B = UniqueKeys0.CONSTRAINT_3B;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord> CONSTRAINT_A2 = UniqueKeys0.CONSTRAINT_A2;
	public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> CONSTRAINT_8A = UniqueKeys0.CONSTRAINT_8A;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_DD2 = ForeignKeys0.CONSTRAINT_DD2;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ContactsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_C = ForeignKeys0.CONSTRAINT_C;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_5A = ForeignKeys0.CONSTRAINT_5A;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_5A7 = ForeignKeys0.CONSTRAINT_5A7;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_5 = ForeignKeys0.CONSTRAINT_5;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_6 = ForeignKeys0.CONSTRAINT_6;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_D = ForeignKeys0.CONSTRAINT_D;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_1 = ForeignKeys0.CONSTRAINT_1;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_A = ForeignKeys0.CONSTRAINT_A;
	public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_8 = ForeignKeys0.CONSTRAINT_8;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<net.phobot.realestate.model.tables.records.ActorsRecord, java.lang.Long> IDENTITY_ACTORS = createIdentity(net.phobot.realestate.model.tables.Actors.ACTORS, net.phobot.realestate.model.tables.Actors.ACTORS.ACTOR_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_3 = createUniqueKey(net.phobot.realestate.model.tables.Actors.ACTORS, net.phobot.realestate.model.tables.Actors.ACTORS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord> CONSTRAINT_DD = createUniqueKey(net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS.REPRESENTATIVE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_6A = createUniqueKey(net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_3C = createUniqueKey(net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.IndividualsRecord> CONSTRAINT_2 = createUniqueKey(net.phobot.realestate.model.tables.Individuals.INDIVIDUALS, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS.ACTOR_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_3B = createUniqueKey(net.phobot.realestate.model.tables.Purchases.PURCHASES, net.phobot.realestate.model.tables.Purchases.PURCHASES.PURCHASE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.AttorneysRecord> CONSTRAINT_A2 = createUniqueKey(net.phobot.realestate.model.tables.Attorneys.ATTORNEYS, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS.REPRESENTATIVE_ID);
		public static final org.jooq.UniqueKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord> CONSTRAINT_8A = createUniqueKey(net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES.ORGANIZATION_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RealEstateAgentsRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_DD2 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6A, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS, net.phobot.realestate.model.tables.RealEstateAgents.REAL_ESTATE_AGENTS.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ContactsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_C = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.Contacts.CONTACTS, net.phobot.realestate.model.tables.Contacts.CONTACTS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_5A = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_5A7 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6A, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.ActorsRepresentativesRecord, net.phobot.realestate.model.tables.records.PurchasesRecord> CONSTRAINT_5 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3B, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES, net.phobot.realestate.model.tables.ActorsRepresentatives.ACTORS_REPRESENTATIVES.PURCHASE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.RepresentativesRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_6 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES, net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.OrganizationsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_D = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS, net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.IndividualsRecord, net.phobot.realestate.model.tables.records.ActorsRecord> CONSTRAINT_1 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS, net.phobot.realestate.model.tables.Individuals.INDIVIDUALS.ACTOR_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.AttorneysRecord, net.phobot.realestate.model.tables.records.RepresentativesRecord> CONSTRAINT_A = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_6A, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS, net.phobot.realestate.model.tables.Attorneys.ATTORNEYS.REPRESENTATIVE_ID);
		public static final org.jooq.ForeignKey<net.phobot.realestate.model.tables.records.TitleCompaniesRecord, net.phobot.realestate.model.tables.records.OrganizationsRecord> CONSTRAINT_8 = createForeignKey(net.phobot.realestate.model.Keys.CONSTRAINT_3C, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES, net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES.ORGANIZATION_ID);
	}
}
