/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2AA26D34_C090_4310_B84E_CA8A5BBD2555</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_2AA26D34_C090_4310_B84E_CA8A5BBD2555 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_2AA26D34_C090_4310_B84E_CA8A5BBD2555", net.phobot.realestate.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
