/**
 * This class is generated by jOOQ
 */
package net.phobot.realestate.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.ACTORS
	 */
	public static final net.phobot.realestate.model.tables.Actors ACTORS = net.phobot.realestate.model.tables.Actors.ACTORS;

	/**
	 * The table PUBLIC.CONTACTS
	 */
	public static final net.phobot.realestate.model.tables.Contacts CONTACTS = net.phobot.realestate.model.tables.Contacts.CONTACTS;

	/**
	 * The table PUBLIC.ACTORSREPRESENTATIVES
	 */
	public static final net.phobot.realestate.model.tables.Actorsrepresentatives ACTORSREPRESENTATIVES = net.phobot.realestate.model.tables.Actorsrepresentatives.ACTORSREPRESENTATIVES;

	/**
	 * The table PUBLIC.REPRESENTATIVES
	 */
	public static final net.phobot.realestate.model.tables.Representatives REPRESENTATIVES = net.phobot.realestate.model.tables.Representatives.REPRESENTATIVES;

	/**
	 * The table PUBLIC.ORGANIZATIONS
	 */
	public static final net.phobot.realestate.model.tables.Organizations ORGANIZATIONS = net.phobot.realestate.model.tables.Organizations.ORGANIZATIONS;

	/**
	 * The table PUBLIC.INDIVIDUALS
	 */
	public static final net.phobot.realestate.model.tables.Individuals INDIVIDUALS = net.phobot.realestate.model.tables.Individuals.INDIVIDUALS;

	/**
	 * The table PUBLIC.PURCHASES
	 */
	public static final net.phobot.realestate.model.tables.Purchases PURCHASES = net.phobot.realestate.model.tables.Purchases.PURCHASES;

	/**
	 * The table PUBLIC.ATTORNEYS
	 */
	public static final net.phobot.realestate.model.tables.Attorneys ATTORNEYS = net.phobot.realestate.model.tables.Attorneys.ATTORNEYS;

	/**
	 * The table PUBLIC.TITLE_COMPANIES
	 */
	public static final net.phobot.realestate.model.tables.TitleCompanies TITLE_COMPANIES = net.phobot.realestate.model.tables.TitleCompanies.TITLE_COMPANIES;
}
